### ISSUE TITLE
Criar índices nas tabelas da base

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#110]
Reunião - campo data
Proposicao - Origem, Autor

**Comment by marcoamarelo** [comment]
Índices criados

CREATE INDEX reuniao_data ON reuniao(data DESC)
CREATE INDEX proposicao_origem ON proposicao(origem)
CREATE INDEX proposicao_autor ON proposicao(autor)
CREATE INDEX proposicao_origem_autor ON proposicao(origem,autor)

**Comment by marcoamarelo** [comment]
Não ajudou muita coisa.... o carregamento parcial terá que ser prioridade na próxima sprint.
