### ISSUE TITLE
Histórico de resultados (andamentos)

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#111]
Fazer do campo resultados uma pilha cronológica, incluindo entradas de tramitação do webservice da camara

**Comment by gcdelgado** [comment]
@rafaelcoutinho e @marcoamarelo a parte que diz "incluindo entradas de tramitação do webservice da camara" quer dizer que cada tramitação irá gerar um novo Andamento automaticamente? Sabem dizer qual é o Service/método que faz esta tramitação, e que deverá inserir o andamento?
