### ISSUE TITLE
Minhas Tarefas Resumida  (tipo balão/notificação FB)

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#114]
Adicionar pessoa responsável pela tarefa, e exibir minhas tarefas para o usuario atual

Adaptar o icone de notificacao do sislegis
![uploads/1dda7a98-7c8c-474a-83c4-8790afb0daa7/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1dda7a98-7c8c-474a-83c4-8790afb0daa7%2Fblob)

**Comment by gcdelgado** [comment]
@POST
	@Path("/marcarVisualizadas")
	@Consumes(MediaType.APPLICATION_JSON)
	public Response marcarComoVisualizadas(List<Integer> idTarefas, @HeaderParam("Referer") String referer){
		tarefaService.marcarComoVisualizadas(idTarefas);
		return Response.noContent().build();
	}

**Comment by gcdelgado** [comment]
ALTER TABLE public.tarefa ADD isvisualizada BOOL DEFAULT FALSE NOT NULL;
