### ISSUE TITLE
Notificação de Alteração da Proposição

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#115]
Adicionar botão de "seguir"  proposição e notificar por email, quando a proposição for alterada.

1. Tem que bater no WS para checar alteracoes diariamente.

**Comment by rafaelcoutinho** [comment]
Serão checados por alteracoes os seguintes campos existentes:

1. Autor
2. Ementa
3. Comissao
4. Numero


E sugiro adicionar 2 novos campos:
1. Situacao
2. Tramitando ou não

@marcoamarelo aprova?

**Comment by marcoamarelo** [comment]
@rafaelcoutinho o que é importante monitorar dessa sua lista é Comissão, Situação e Tramitação. Outras que são muito importantes e que a Aspar precisa muito são alterações no texto da proposição com a apresentação de emendas e substitutivos.

**Comment by rafaelcoutinho** [comment]
No senado consigo ver alteracoes na ementa:
http://legis.senado.leg.br/dadosabertos/materia/113361?v=4
Vou concatenar a EmentaMateria com ExplicacaoEmentaMateria e verificar alteração nas duas.

Acho que só isso que consigo checar do texto.


 Substitutivos, não sei o que são, você @marcoamarelo  pode apontá-los aí no WS do senado?

**Comment by rafaelcoutinho** [comment]
Já na câmara, só a ementa mesmo:
http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterProposicaoPorID?idProp=562039

**Comment by marcoamarelo** [comment]
Fala @rafaelcoutinho. Verifiquei dois exemplos de proposições que tiveram a apresentação de substitutivos: Câmara PL 613/2015 e no Senado o PLS 141/2013. 

Parece que na Câmara a informação do histórico da matéria é mais difícil de obter. Não achei nada nos webservices, mas achei essa página do 613 que é exatamente a informação que precisamos monitorar: http://www.camara.gov.br/proposicoesWeb/prop_pareceres_substitutivos_votos?idProposicao=964621

No Senado, ao contrário, não achei clara a informação sobre substitutivos da matéria, mas no webservice existe um campo <TextoTramitacao> que contém o que precisamos. O que você acha? Será que existe algum webservice que possa conter as informações da câmara que não estamos achando? Se não, parsear o html você acha complicado?

**Comment by rafaelcoutinho** [comment]
@marcoamarelo Estranho q o link pra mim dá serviço não disponível.

**Comment by rafaelcoutinho** [comment]
mudar seguir para seguindo
