### ISSUE TITLE
Funçao  de conclusão de tarefa

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#116]
Permitir que o usuário conclua a tarefa e insira um comentário que estará associado às proposição relacionada do encaminhamento desta tarefa

**Comment by gcdelgado** [comment]
Backend implementado. Precisamos agora decidir se alteramos o frontend antigo, ou deixamos para fazer só no novo. @marcoamarelo e @rafaelcoutinho o que acham? Criamos nova issue?

**Comment by marcoamarelo** [comment]
Na hora que o @theoziran publicar a nova branch com a base do novo tema
instalado, vale você baixar a branch dele na sua e já preparar o frontend,
mesmo que depois o @theoziran ou o @thsl entrem pra melhorar.

Abraços.

Marco Antonio Konopacki
@marcoamarelo
-------
...... __@
...._ \ >_
...(_)/ (_)

Em 15 de outubro de 2015 00:42, Gustavo Cesar Delgado <
notifications@github.com> escreveu:

**Comment by gcdelgado** [comment]
Comentário da finalização da tarefa deve entrar na pilha de comentários padrão da proposição.

**Comment by rafaelcoutinho** [comment]
EncaminhamentoProposicao terá 
- Campo ComentárioFinalizacao do tipo comentaraio (provavelmente sera o campo atual chamado comentario) está associado a Proposição.
- Campo String com o titulo/descricao do encaminhamenot (por exemplo "Da deputada Joana")

Este terá uma pilha de comentário da Proposicao associado. 

Terá uma tarefa.

Será permitido finalizar uma tarefa ela também finaliza o EncaminhamentoProposicao. Se sim copiamos o id do comentario de finalizacao da tarefa para o ComentárioFinalizacao. 

O tipo Encaminhamento está ERRADO, deve ser TipoEncaminhamento.

Permitir também a finalizacao do EncaminhamentoProposicao direto nele, e neste momento finaliza as tarefas associadas.

**Comment by gcdelgado** [comment]
Executar SQL antes do deploy:

**ALTER TABLE public.encaminhamento RENAME TO tipo_encaminhamento;**
