### ISSUE TITLE
Fragmentação do carregamento da Reunião

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#121]
Lazyloading do comentários e encaminhamentos. E estudar quais outros são necessários.

**Comment by gcdelgado** [comment]
Primeiro passo: remover ProposicaoJSON do projeto para evitar as inúmeras conversões que estão espalhadas pelo código, sendo que Proposicao e ProposicaoJSON são praticamente iguais.
@rafaelcoutinho favor verificar se em suas últimas implementações, foi utilizada a ProposicaoJSON para alguma coisa. Já alterei aqui para trabalhar apenas com a entidade.

**Comment by rafaelcoutinho** [comment]
@gcdelgado não mexi em nada que se baseie nisso, pode mandar ver.

**Comment by gcdelgado** [comment]
Removida também a classe EncaminhamentoProposicaoJSON, substituindo pela entidade

**Comment by gcdelgado** [comment]
@rafaelcoutinho, @marcoamarelo : fiz mandei os pull requests tanto do backend quanto do frontend, deem uma conferida por favor.
@rafaelcoutinho como foram muitas alterações, este merge pode dar algum conflito, ainda falta terminar a fragmentação da lista de encaminhamentos, mas conforme conversamos, é melhor fazer o merge parcial (com esta parte que está funcionando).
