### ISSUE TITLE
Página de impressão da Proposição

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#125]
Uma página fixa com todos os dados (e histórico) exibidos nela. De pref com uma url amigavel. 

Histórico contém:
Lista de comentários
Lista de encaminhamentos
Reuniões que ela pertenceu
Em quais comissões ela estava
Lista de Resultados

**Comment by rafaelcoutinho** [comment]
Usar o endpoint atual de proposição
/proposicaos/123

**Comment by marcoamarelo** [comment]
@theoziran eu vi que você gerou o link de impressão. Quando eu chamar esse endereço sugerido pelo @rafaelcoutinho ele vai exibir o modal com os dados da preposição?

**Comment by rafaelcoutinho** [comment]
adiado para 15.10.02

**Comment by marcoamarelo** [comment]
ISSO É UMA PÁGINA NÃO UM MODAL!!!!

**Comment by rafaelcoutinho** [comment]
movido para sprint 15.11.01
