### ISSUE TITLE
Inclusão do UserReport do Sislegis

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#136]
Inclusão do UserReport para coletar ideias para o Sislegis

**Comment by theoziran** [comment]
@marcoamarelo o UserReport no lado esquerdo fica em cima do menu acho que seria melhor do outro lado.
![uploads/dc4bc2a8-1194-4b69-89bd-d1348f99e7f6/Screen Shot 2015-10-27 at 9.44.30 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdc4bc2a8-1194-4b69-89bd-d1348f99e7f6%2FScreen+Shot+2015-10-27+at+9.44.30+PM.png)

**Comment by marcoamarelo** [comment]
Sim @theoziran, eu imaginei que ia rolar isso, mas não mexi no estilo por
motivos óbvios hehehe. Eu queria esse ícone no canto inferior direito, pode
fazer isso pra mim? Cria uma issue.

Marco Antonio Konopacki
@marcoamarelo
-------
...... __@
...._ \ >_
...(_)/ (_)

Em 27 de outubro de 2015 21:46, Theoziran Lima <notifications@github.com>
escreveu:
