### ISSUE TITLE
Montagem Manual de Pauta - Permitir inclusão de proposição da base numa reunião

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#142]
Hoje só se inclui proposicoes que estejam na pauta de uma comissão. Deseja-se permitir incluir qqer q esteja no banco do sislegis.

**Comment by rafaelcoutinho** [comment]
Lembrar que pode permitir ao usuario incluir dados da pauta dessa proposicao: Como OrdemNaPauta, Relator

**Comment by thsl** [comment]
inclusão de proposição fora de pauta

![uploads/b1ad7e33-e4bf-4c09-9c3b-9396f02c7e49/tela-reuniao-add-fora.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb1ad7e33-e4bf-4c09-9c3b-9396f02c7e49%2Ftela-reuniao-add-fora.gif)
