### ISSUE TITLE
Atualizar rotulo comentário do encaminhamento

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#143]
Quando faz um encaminhamento há um campo chamado comentário, mas devia ser algo diferente de comentário

**Comment by rafaelcoutinho** [comment]
@theoziran Esta issue está bloqueada pela sua issue do admin LTE. Me avise para poder fazê-la.

**Comment by marcoamarelo** [comment]
Não entendi @rafaelcoutinho ?? A tarefa tá bloqueada, mas marcada ready for next stage?
