### ISSUE TITLE
UI da lista de resultado

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#145]
Permitir seleção de data e descrição

**Comment by rafaelcoutinho** [comment]
Adiada pra 15.10.02

**Comment by gcdelgado** [comment]
@theoziran no backend desta issue, chamei os resultados de "Andamentos" pois usamos este nome em algumas conversas lá no MJ, já que eles representam uma sequência de fatos. 
O endpoint que vc vai usar é AndamentoEndpoint. Se todos acharem melhor renomear tudo para Resultado ao invés de Andamento, avisem que já altero, pois é melhor fazer isso antes de vc criar a interface.

**Comment by marcoamarelo** [comment]
Remover a opção de atualizar resultados (legado).

**Comment by theoziran** [comment]
@gcdelgado voltamos pra resultado

**Comment by rafaelcoutinho** [comment]
movido para sprint 15.11.01

**Comment by rafaelcoutinho** [comment]
@theoziran Como ficou esse? Vamos mover pro novo sprint?
