### ISSUE TITLE
Adaptar Admin LTE

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#147]

**Comment by rafaelcoutinho** [comment]
adiado para 15.10.02

**Comment by rafaelcoutinho** [comment]
De uma olhada pq não abre a modal de adicao de proposicao avulsa

**Comment by theoziran** [comment]
Foi removido nesse merge https://github.com/pensandoodireito/sislegis-app-frontend/commit/dd0a0a9be9f5b13f10113138a8a07092831b3711 irei adicionar de volta.
