### ISSUE TITLE
Ao entrar na página de tarefas está dando um warning de JS

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#150]
![uploads/592bc45b-4789-4a4b-bdb4-f75d852a30b1/warning.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F592bc45b-4789-4a4b-bdb4-f75d852a30b1%2Fwarning.png)

**Comment by gcdelgado** [comment]
Resolvido com a migração para nova UI
