### ISSUE TITLE
Obter dados do relator para proposição

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#159]
Existem dados de relatoria nas pautas. Portanto poderemos obter esses dados sempre que for incluida a proposicao na pauta da semana.

Este campo está nos dois webservices.

http://legis.senado.leg.br/dadosabertos/reuniao/834
http://www.camara.gov.br/SitCamaraWS/Orgaos.asmx/ObterPauta?IDOrgao=2003&datIni=20151012&datFim=20151015&v=4

Vamos guardar o histórico de relatorias com suas respectivas comissoes

**Comment by rafaelcoutinho** [comment]
Inclusive no parser do senado devemos ignorar as materiarelacionadas de evento, somente as dos itens.
