### ISSUE TITLE
Permitir Remover Posicionamento

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#167]

**Comment by rafaelcoutinho** [comment]
Sempre criar a proposicao com SEM POSICIONAMENTO. E permitir re associa-lo no futuro. 

E mexer no filtro.

Deve contemplar script de importacao.

**Comment by gcdelgado** [comment]
@rafaelcoutinho e @marcoamarelo - possibilidade de salvar proposição sem posicionamento já está implementada. Dúvidas:

1. O que deve ser mexido no filtro?

2. Script de importação de que? A Issue #169 pede um histórico de alterações de posicionamento. Sempre que for alterado, será salvo o posicionamento anterior no histórico, mas não entendi em que momento será preciso script para importação.

**Comment by gcdelgado** [comment]
Alteração feita no filtro, com função para verificar se o posicionamento é nulo ou não.

Sugestão: criar nova issue de UI para rever o filtro, pois não existe botão para se "zerar" os filtros. Quando se marca uma vez "Posicionamento não definido", só há possibilidade de exibir os definidos ou não (não dá para exibir todos juntos novamente).

**Comment by marcoamarelo** [comment]
@gcdelgado, vamos falar amanhã sobre essa issue. Sobre a importação, pensei
que deveria ser feito um ajuste para trazer os posicionamentos defnidos
hoje para o novo modelo criado. Se isso não irá precisar então acho que não
precisamos dessa tarefa.

Abraços.

Marco Antonio Konopacki
@marcoamarelo
-------
...... __@
...._ \ >_
...(_)/ (_)

Em 3 de novembro de 2015 17:53, Gustavo Cesar Delgado <
notifications@github.com> escreveu:

**Comment by gcdelgado** [comment]
Obrigado @marcoamarelo. Sobre a importação, depois vi que vai precisar sim, mas na Issue #169, e não nessa.

**Comment by gcdelgado** [comment]
Fazer junto com a Issue #169 na próxima sprint
