### ISSUE TITLE
Garantir rastreabilidade histórica do posicionamento da proposição

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#169]

**Comment by rafaelcoutinho** [comment]
Quando alterar o posicionamento para conter  quem e quando e m histórico.em proposicao

**Comment by gcdelgado** [comment]
Permitir deixar o posicionamento em branco (vazio), antiga issue #167

**Comment by gcdelgado** [comment]
PRs enviados em backend e frontend

**Comment by gcdelgado** [comment]
Listagem do histórico no Frontend: issue 195
