### ISSUE TITLE
Desenhar a tela de execução de reunião

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#182]
1) Exibir a área de proposição redesenhada e mais enxuta;
2) Destaque do encaminhamento;
3) Filtro stick e organizado por funcionalidades mais usadas (casa leg, comissão e texto livre). Botão mais para collapse responsável, posicionamento, etc.
4) Collapse das proposições e marcação de proposições que já foram revisadas;
5) Modal quando houver explicação da ementa;
6) Listagem de resultados/tramitação;

**Comment by rafaelcoutinho** [comment]
movido para sprint 15.11.01

**Comment by thsl** [comment]
1) Exibir a área de proposição redesenhada e mais enxuta;

![uploads/c2ec8b9b-503b-4a3d-91dc-a4bb695892a0/tela-reuniao-proposicao-aberta.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc2ec8b9b-503b-4a3d-91dc-a4bb695892a0%2Ftela-reuniao-proposicao-aberta.png)

**Comment by thsl** [comment]
2) Destaque do encaminhamento;

![uploads/97459fbc-9917-4d2e-b4ad-7cb20d086fe7/tela-reuniao-proposicao-encaminhamento.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F97459fbc-9917-4d2e-b4ad-7cb20d086fe7%2Ftela-reuniao-proposicao-encaminhamento.gif)

**Comment by thsl** [comment]
4) Collapse das proposições e marcação de proposições que já foram revisadas;

![uploads/5e10f1a6-bdf7-4f48-91f7-d732dab8bda1/tela-reuniao-proposicao-collapse.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5e10f1a6-bdf7-4f48-91f7-d732dab8bda1%2Ftela-reuniao-proposicao-collapse.gif)

**Comment by thsl** [comment]
5) Modal quando houver explicação da ementa;

![uploads/40f487eb-f3bc-4b12-bac4-d1e7e3ee864b/tela-reuniao-detalha-ementa.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F40f487eb-f3bc-4b12-bac4-d1e7e3ee864b%2Ftela-reuniao-detalha-ementa.gif)
