### ISSUE TITLE
Tela de gerenciamento de reunião

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#183]
1) Exibir a lista de reuniões;
2) Pesquisa de reuniões por mês;
3) Botão de inclusão de proposições;
4) Inclusão de proposição avulsa;
5) Atualização manual de proposição (botão);
6) Listagem de resultados/tramitação;
7) Na tela de inclusão de proposição, exibir o último comentário do sislegis, se houver.

**Comment by marcoamarelo** [comment]
![uploads/8b71de4a-b164-4c67-bcc8-5d774d08f592/prot-proposicao.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8b71de4a-b164-4c67-bcc8-5d774d08f592%2Fprot-proposicao.jpg)

![uploads/86e7984b-ce84-46c6-b864-e2d3186abce3/prot-telas.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F86e7984b-ce84-46c6-b864-e2d3186abce3%2Fprot-telas.jpg)

**Comment by rafaelcoutinho** [comment]
movido para sprint 15.11.01

**Comment by thsl** [comment]
Opção de interação:

![uploads/914a8d4f-f669-489d-9344-7016c119df66/tela-reuniao-001.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F914a8d4f-f669-489d-9344-7016c119df66%2Ftela-reuniao-001.gif)
