### ISSUE TITLE
Criação do serviço para atualização de andamento a partir dos webservices Câmara e Senado

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#193]
Definir o que fazer com o antigo campo resultados

**Comment by rafaelcoutinho** [comment]
Mudamos o nome da entity - andamento

**Comment by gcdelgado** [comment]
Renomeando todas as classes/serviços de Andamento para Resultado, conforme conversado na reunião da sprint em 30/10.

**Comment by gcdelgado** [comment]
**Instruções para o deploy:**

1. Verificar após o deploy se a tabela "resultado" foi criada
2. Excluir a tabela "andamento"

**Comment by gcdelgado** [comment]
Verificar com @rafaelcoutinho como será o relacionamento dos resultados após a nova modelagem. Hoje coloquei relacionando com ReuniaoProposicao.

**Comment by gcdelgado** [comment]
@rafaelcoutinho e @marcoamarelo atualizei minha branch conforme entendimento até o momento desta issue. Mas preciso que vocês avaliem alguns detalhes, por exemplo:
A busca de PautaReuniaoComissao foi feita considerando o campo "situacao" para pegar todas as reuniões com data anterior à data atual, e com situação ainda pendente, e que portanto ainda podem sofrer alteração no resultado. Não sei quais são as possíveis situações que representam "pendência" pois o campo situacao é String.
No agendamento, esta verificação seria feita todos os dias às 4h da manhã.
Amanhã será preciso alinhar com o Rafael estes últimos detalhes, antes de enviarmos o PR.
