### ISSUE TITLE
UI para histórico posicionamentos

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#195]

**Comment by rafaelcoutinho** [comment]
movido para sprint 15.11.01

**Comment by gcdelgado** [comment]
Backend: issue 169
Endpoint para a listagem do histórico: proposicaos/historicoPosicionamentos/id_da_proposicao

**Comment by thsl** [comment]
Proposta (o restante aparecerá no single de pauta) 

![uploads/51707185-e653-4154-9f71-a951cc5b069e/tela-ultimo-posicionamento.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F51707185-e653-4154-9f71-a951cc5b069e%2Ftela-ultimo-posicionamento.png)

**Comment by thsl** [comment]
Modal:

![uploads/9427173a-f453-450d-9740-d6e174487640/tela-todos-posicionamentos.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9427173a-f453-450d-9740-d6e174487640%2Ftela-todos-posicionamentos.gif)
