### ISSUE TITLE
Na listagem de tarefa, a identificação da proposição está como null null/null

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#200]
Não esqueça de fazer isso como fix da release-15.10.01 e depois integrar ao develop esse commit.

**Comment by gcdelgado** [comment]
@marcoamarelo este problema foi corrigido na última sexta-feira junto com outros hotfixes, no PR:
https://github.com/pensandoodireito/sislegis-app-frontend/pull/36/files do @rafaelcoutinho.
E já foi integrado na branch master. Como podemos proceder?

**Comment by marcoamarelo** [comment]
Verdade @gcdelgado.

Em produção está funcionando. O curioso é que o coutinho tinha os hotfixes
ao develop. Pode verificar isso com ele amanhã?

Abraços.

Marco Antonio Konopacki
@marcoamarelo
-------
...... __@
...._ \ >_
...(_)/ (_)

Em 26 de outubro de 2015 21:42, Gustavo Cesar Delgado <
notifications@github.com> escreveu:

**Comment by rafaelcoutinho** [comment]
Acho q eu ja tinha mergeado isso

**Comment by marcoamarelo** [comment]
pois é, bem estranho Rafael.

E agora? Alguém pode investigar a partir do branch de release o que passa
então?

Marco Antonio Konopacki
@marcoamarelo
-------
...... __@
...._ \ >_
...(_)/ (_)

Em 27 de outubro de 2015 09:14, Rafael Coutinho <notifications@github.com>
escreveu:

**Comment by gcdelgado** [comment]
Foi integrado na branch master do Frontend no PR que passei acima. Depois disso, algum outro merge deve ter sobrescrito as alterações. Vi que na branch develop, elas estão lá.

**Comment by gcdelgado** [comment]
Pessoal, foi preciso fazer uma correção no backend também por conta deste Null Null das tarefas. Mesmo com a alteração do frontend, ainda estava com erro (apesar de eu e o Rafael termos testado na sexta e parecia estar ok, mas enfim...). 
@marcoamarelo e @rafaelcoutinho: podem validar o PR 201 por favor? Precisarei destas alterações integradas em develop para resolver uma outra Issue (lazy load dos encaminhamentos). Nela serão retiradas algumas coisas que estão "bem feias" no código, como o método getProposicao() da entidade EncaminhamentoProposicao.

**Comment by gcdelgado** [comment]
Novo PR enviado. @rafaelcoutinho implementei o JsonSerializer. Pode conferir?
