### ISSUE TITLE
Remodelagem da apresentação de filtros

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#215]

**Comment by thsl** [comment]
Sugestão: (filtros fixos no topo da listagem e complementos no slider no lado direito)

![uploads/fe26eceb-4007-4f8f-b09d-2aefac774d53/tela-reuniao-filtros.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffe26eceb-4007-4f8f-b09d-2aefac774d53%2Ftela-reuniao-filtros.gif)

**Comment by thsl** [comment]
Opção dos filtros:

![uploads/613b893f-bacb-40bc-871d-390c3a05d3a0/tela-reuniao-filtros.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F613b893f-bacb-40bc-871d-390c3a05d3a0%2Ftela-reuniao-filtros.png)
