### ISSUE TITLE
Criação da categoria de posicionamentos preliminares (Previamente)

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#216]

**Comment by gcdelgado** [comment]
Frontend: issue #51

**Comment by gcdelgado** [comment]
posicionamento_proposicao é quem terá a informação de posicionamento preliminar ou não.
No banco de dados não existirá mais o posicionamento na proposicao - será @Transient.
@marcoamarelo e @rafaelcoutinho favor verificar o PR, principalmente as operações que serão executadas no banco.
@theoziran a mágica para detectar e setar os posicionamentos preliminares deverá ser feita pelo filtro na tela. O objeto está sendo retornado com um boolean - posicionamentoPreliminar.
