### ISSUE TITLE
Ajustar adição de tags em proposição

### ISSUE THREAD

**Issue by theoziran** [pensandoodireito/sislegis-app#243]

**Comment by theoziran** [comment]
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "text" (class br.gov.mj.sislegis.app.model.TagProposicao), not marked as ignorable (3 known properties: "tag", "tagProposicaoPK", "proposicao"]) at [Source: io.undertow.servlet.spec.ServletInputStreamImpl@451dde1c; line: 1, column: 727] (through reference chain: br.gov.mj.sislegis.app.model.Proposicao["tags"]->br.gov.mj.sislegis.app.model.TagProposicao["text"])

**Comment by gcdelgado** [comment]
Duplicada #242
