### ISSUE TITLE
Planejar interface de criação de roadmap

### ISSUE THREAD

**Issue by theoziran** [pensandoodireito/sislegis-app#248]

**Comment by thsl** [comment]
Entrevistar a aspar sobre a aplicação.

**Comment by thsl** [comment]
Sugestão:

![uploads/9d8dfada-cd81-4e23-a35e-21a730782bde/tela-roadmap.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9d8dfada-cd81-4e23-a35e-21a730782bde%2Ftela-roadmap.gif)
