### ISSUE TITLE
Migrar os "posicionamentos preliminares" para uma único item

### ISSUE THREAD

**Issue by theoziran** [pensandoodireito/sislegis-app#249]

**Comment by gcdelgado** [comment]
update posicionamento_proposicao set posicionamento_id = 3, preliminar = TRUE where posicionamento_id = 11;
update posicionamento_proposicao set posicionamento_id = 6, preliminar = TRUE where posicionamento_id = 12;
update posicionamento_proposicao set posicionamento_id = 8, preliminar = TRUE where posicionamento_id = 13;
update posicionamento_proposicao set posicionamento_id = 9, preliminar = TRUE where posicionamento_id = 14;
update posicionamento_proposicao set posicionamento_id = 10, preliminar = TRUE where posicionamento_id = 15;

delete from posicionamento_proposicao where posicionamento_id in (11, 12, 13, 14, 15);

**Comment by marcoamarelo** [comment]
Deletar da tabela posicionamento, não da posicionamento_proposicao
