### ISSUE TITLE
UI para edição de pauta de proposição adicionada avulso

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#279]
Quando uma proposicao é adicionada de maneira avulsa deve-se permitir ao usuário editar os dados da pauta comissao manualmente
Podendo informar:
Ordem de pauta
Relatoria
Codigo reuniao
Data e hora reuniao (por default a data é a da busca)

**Comment by thsl** [comment]
Protótipo:
http://pensandoodireito.github.io/sislegis-prototipo/prototipo
