### ISSUE TITLE
Busca no webservice da câmara só trás a pauta da semana passada

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#28]
Boa tarde Marco, tudo bem?

Então, acrescentei na pauta os projetos que estavam na pauta desta semana, mas que não foram deliberados, pois não consegui encontrar a pauta da semana que vem pelo sistema.

Continua com aquele probleminha.

Mas conforme combinamos, acrescentei os que continuam na pauta, mas os números dos itens estão errados.

Por enquanto é só.

Bom final de semana!

**Comment by rafaelcoutinho** [comment]
Sendo tratada na issue #142

**Comment by rafaelcoutinho** [comment]
mentira eheh .. .tratando agora
