### ISSUE TITLE
Centralizar mock ups 

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#283]

**Comment by thsl** [comment]
Criamos este repo no Git https://github.com/pensandoodireito/sislegis-prototipo. Porém a página ficava com muitos erros e este protótipo logo ficou obsoleto.

Porém consegui resgatá-lo e também consegui fazê-lo fazer funcionar de forma correta, no link http://pensandoodireito.github.io/sislegis-prototipo/prototipo/
