### ISSUE TITLE
Correção da impressão de pauta

### ISSUE THREAD

**Issue by gcdelgado** [pensandoodireito/sislegis-app#300]

**Comment by rafaelcoutinho** [comment]
@marcoamarelo Subi o fix para o release 15.11.01. Esta em 2 PRs para o back e frontend

**Comment by rafaelcoutinho** [comment]
@theoziran Por algum motivo aparece tudo ok na primeira modal de impressao, mas qdo clica em imprimir nela, a segunda como preview remove os comentários. Acho que vc pode arrumar isso. O backend está feito e fiz também a parte do frontend. 
fyi @marcoamarelo

**Comment by rafaelcoutinho** [comment]
Eis os PRs:
Frontend https://github.com/pensandoodireito/sislegis-app-frontend/pull/82
Backend https://github.com/pensandoodireito/sislegis-app/pull/305
