### ISSUE TITLE
UI não está montadando o campo de posicionamento com o "Previamente" na frente quando o posicionamento é preliminar

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app#319]

**Comment by theoziran** [comment]
A issue pensandoodireito/sislegis-app#51 não havia sido integrada. Fiz o merge com develop e testei está funcionando corretamente.

**Comment by marcoamarelo** [comment]
Oi Theo, preciso que você integre esse commit específico ao máster. Sugiro
fazer um Cherry pick pra não jogar coisa demais no máster.

Obrigado!
Em 16 de dez de 2015 8:57 AM, "Theoziran Lima" <notifications@github.com>
escreveu:
