### ISSUE TITLE
Frontend para exibir votação na single de proposição

### ISSUE THREAD

**Issue by gcdelgado** [pensandoodireito/sislegis-app#349]
Backend: Issue 170

**Comment by gcdelgado** [comment]
Objetos / campos

Votacao

dataHora
resultado
descricao
votos (listagem de votos)
Voto

nomeParlamentar
partidoParlamentar
ufParlamentar
descricaoVoto

**Comment by theoziran** [comment]
Implementado na single de proposição, mas tenho algumas considerações:
- Buscar para o Senado e Câmara com parâmetros diferentes. Exemplo: Senado se busca com idProposicao que não é o nosso proposicaoId isso está um pouco confuso. E para buscar para Câmara está sendo buscado pelo número, tipo e ano. O serviço poderia pedir apenas nosso identificador de proposição e internamente resolveria como seria a chamada para cada casa, seria necessário apenas o idProposiçõa e talvez a origem: Senado ou Câmara;
- Na resposta do voto poderia ter a saída ser:
  {nome, partido, uf, voto, thumb};
- Trazer nome do parlamentar ao invés do nome completo.

@gcdelgado @rafaelcoutinho @marcoamarelo
